// <auto-generated />
namespace GUI_eksamen___Opgave_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newstuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newstuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201806181714322_newstuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
